SRC_Hubert/ACME_HomeLoanSystem/ACME_HomeLoanSystem-war/src/java/beans/WebLoginBean.java
package beans;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.annotation.Resource;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.Dependent;
import javax.enterprise.context.SessionScoped;
import javax.enterprise.inject.Produces;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.event.ComponentSystemEvent;
import javax.jms.Connection;
import javax.jms.ConnectionFactory;
import javax.jms.Destination;
import javax.jms.JMSConsumer;
import javax.jms.JMSContext;
import javax.jms.JMSException;
import javax.jms.JMSProducer;
import javax.jms.Message;
import javax.jms.MessageConsumer;
import javax.jms.MessageProducer;
import javax.jms.Session;
import javax.jms.TextMessage;

/**
 *
 * @author JamesAlan
 */
@Named(value = "webLoginBean")
@ManagedBean
// available throughout the users session
@SessionScoped
public class WebLoginBean implements Serializable
{
//    @ManagedProperty(value="#{webJMSService}")
//    private JMSService jmsService=new JMSService();
 
    //private static final long serialVersionUID = 661;
//    @EJB    
//    private UserBeanRemote customerSessionBean; 
    
    @Resource(name="jms/DBQueueFactory")
    private ConnectionFactory dbQueueFactory;
    @Resource(name="jms/ClientQueueFactory")
    private ConnectionFactory clientQueueFactory;
    @Resource(name="jms/DBQueue")
    private Destination dbQueue;
    @Resource(name="jms/ClientQueue")
    private Destination clientQueue;
    
    private String id, password, error;
    private boolean isAuth;
    
//    public void setJMSService(JMSService jmsService) {
//        this.jmsService = jmsService;
//    }
    /**
     * Creates a new instance of WebLoginBean
     */
    public WebLoginBean() 
    {        
    }
    
    @PostConstruct
    public void initialize() 
    {
        isAuth = false;
        error = "";
    }

    @PreDestroy
    public void close()
    {
        id = null;
        password = null;
        isAuth = false;
    }
    
    public String getError() { return error; }
    public String getId() { return id; }
    public String getPassword() { return password; }

    public void isAuthenticated() throws IOException
    {
        if (!this.isAuth)
        {
            System.out.println("Authentication failed, redirecting");
            FacesContext.getCurrentInstance().getExternalContext().redirect("sessionTimeout.xhtml");
        }
    }
    
    public void setId(String id) { this.id = id.toUpperCase(); }
    public void setPassword(String password) { this.password = password; }
    
    
    public String getWelcomeMessage()
    {
        //TODO get actual person's name
        return String.format("Wilkommen, %s!", id);
    }
    private boolean JMSLogin(String CID, String pw){
        boolean loginSuccessful=false;
        JMSContext jmsContext=dbQueueFactory.createContext();
        JMSContext clientContext=clientQueueFactory.createContext();
        JMSProducer producer=jmsContext.createProducer();            
        try{            
            TextMessage tm = jmsContext.createTextMessage();
            tm.setJMSReplyTo(clientQueue);
            tm.setText("L:"+CID+" "+pw);
            producer.send(dbQueue,tm); 
            JMSConsumer consumer = clientContext.createConsumer(clientQueue,"JMSCorrelationID='"+tm.getJMSMessageID()+"'"); 
            TextMessage replyMessage = (TextMessage)consumer.receive();
            String m=replyMessage.getText();
            System.out.println("Receive Feedback: "+m);
            if (m.charAt(0)=='L' && m.charAt(2)=='T'){
                loginSuccessful=true;
            }
        }catch(JMSException e1){
        }
        return loginSuccessful;
    }
    public String initMe() //throws JMSException
    {
        this.error = "";
        boolean loginSeccessful=false;
        loginSeccessful=JMSLogin(this.id, this.password);
        //loginSeccessful=customerSessionBean.login(this.id, this.password);
        //loginSeccessful=jmsService.jmsLogin(this.id, this.password);
                
        /** Redirect to welcome page and setup session context variable if successful **/
        if (loginSeccessful)
        {    
            System.out.println("ACME LOGIN SUCCESS");
            
            //TODO use this?
            FacesContext context = FacesContext.getCurrentInstance();
            context.getExternalContext().getSessionMap().put("loginid", this.id);
            
            this.isAuth = true;
            
            //session.setAttribute("loginid", this.id);
            return "welcome";
        }
        
        /** Display error message in the <p:messages> panel  **/
        System.out.println("ACME LOGIN FAILED");
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,"Invalid Username or Password", "More info"));
        
        this.error = "Invalid ID or password.  Please try again.";
        //FacesContext context = FacesContext.getCurrentInstance();
        //context.addMessage(errorMsg.getClientId(), new FacesMessage("FAIL"));
        return "login";
    }
    
    public String logout()
    {
        close();
        return "login";
    }
}

SRC_Hubert/ACME_HomeLoanSystem/ACME_HomeLoanSystem-war/web/Transactions.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Welcome to ACME banking!</title>
        <f:event type="preRenderView" listener="#{webLoginBean.isAuthenticated()}" />
    </h:head>
    <h:body>
        
        <!-- Include the decoration container -->
            <ui:decorate template="decor.xhtml">
                <!-- A container for the content (content defined in decor.xhtml) -->
                <ui:define name="content">
                    <!-- include the menu -->
                    <ui:include src="menuBar.xhtml"/>
                    
                    <!-- Home page form -->
                    <p:layoutUnit position="center" resizable="false" style="min-height: 400px;max-height: available">
                        <h:form>
                            <!-- Transactions -->
                            <p:messages id="messages" autoUpdate="true" closable="true"/>
                            <h:panelGrid columns="2" columnClasses="rightalign,leftalign,leftalign">
                                
                                <!-- From Account (Savings Accounts) -->
                                <h:outputText value="From Savings: *" />
                                <p:selectOneMenu value="#{webTransactionsBean.fromAccountID}" >
                                    <f:selectItem itemLabel="Select One" itemValue="" />
                                    <f:selectItems value="#{webTransactionsBean.sAccs}" />
                                </p:selectOneMenu>
                                
                                <!-- To Account (Home Loan Accounts) -->
                                <h:outputText value="From Savings: *" />
                                <p:selectOneMenu value="#{webTransactionsBean.toAccountID}" >
                                    <f:selectItem itemLabel="Select One" itemValue="" />
                                    <f:selectItems value="#{webTransactionsBean.hlAccs}" />
                                </p:selectOneMenu>
                                
                                <!-- Amount  -->
                                <h:outputText value="Amount: *" />
                                <p:spinner id="amount"
                                                 value="#{webTransactionsBean.amount}" min="0"/>  
                                
                                <p:commandButton value="Submit" 
                                                    actionListener="#{webTransactionsBean.submit}"/>
                            </h:panelGrid>
                            
                            <!-- accounts table -->
                            
                        </h:form>
                    
                    </p:layoutUnit>
                </ui:define>
            </ui:decorate>
        
    </h:body>
</html>

SRC_Hubert/ACME_HomeLoanSystem/ACME_HomeLoanSystem-war/web/about.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>ACME Bank Assignment 2</title>
        <f:event type="preRenderView" listener="#{webLoginBean.isAuthenticated()}" />
    </h:head>
    <h:body>
        
        <!-- Include the decoration container -->
            <ui:decorate template="decor.xhtml">
                <!-- A container for the content (content defined in decor.xhtml) -->
                <ui:define name="content">
                    <!-- include the menu -->
                    <ui:include src="menuBar.xhtml"/>
                    
                    <!-- Home page form -->
                    <p:layoutUnit position="center" resizable="false" style="min-height: 400px;max-height: available">
                    <h:outputText value="Application by Christopher White, Hongtao Wu and James Alan Nguyen, 2013" />
                        
                    </p:layoutUnit>
                </ui:define>
            </ui:decorate>
        
    </h:body>
</html>

SRC_Hubert/ACME_HomeLoanSystem/ACME_HomeLoanSystem-war/web/accounts.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Welcome to ACME banking!</title>
        <f:event type="preRenderView" listener="#{webLoginBean.isAuthenticated()}" />
    </h:head>
    <h:body>
        
        <!-- Include the decoration container -->
            <ui:decorate template="decor.xhtml">
                <!-- A container for the content (content defined in decor.xhtml) -->
                <ui:define name="content">
                    <!-- include the menu -->
                    <ui:include src="menuBar.xhtml"/>
                    
                    <!-- Home page form -->
                    <p:layoutUnit position="center" resizable="false" style="min-height: 400px;max-height: available">
                    <h:outputText value="#{webLoginBean.welcomeMessage}" />
                    
                        <h:form>
                            <h:panelGrid columns="3"
                                         columnClasses="rightalign,leftalign,leftalign">
                                <h:commandButton id="refresh" value="Refresh"
                                                 action="accounts"/>
                                <h:commandButton id="logout" value="Logout"
                                                 action="#{webLoginBean.logout}"/>
                            </h:panelGrid>
                            
                            <!-- accounts table -->
                            <p:panel header ="Savings Accounts" style="padding: 20px; margin: 20px; max-width: 600px">
                                <p:dataTable summary="Savings Accounts" id="saccounts" var="account" value="#{WebAccountsBean.accounts}">
                                    <p:column headerText="Account ID">
                                        <h:outputText value="#{account.accNum}" />  
                                    </p:column>
                                    <p:column headerText="Balance">
                                        <h:outputText value="#{account.balance}" />
                                    </p:column>

                                </p:dataTable>
                            </p:panel>
                            <br/>
                            <!-- accounts table -->
                            <p:panel header ="Home Loan Accounts" style="padding: 20px; margin: 20px; max-width: 600px">
                                <p:dataTable  summary="Home Loan Accounts" id="hlaccounts" var="account" value="#{WebAccountsBean.accounts}">
                                    <p:column headerText="Account ID">
                                        <h:outputText value="#{account.accNum}" />  
                                    </p:column>
                                    <p:column headerText="Amount Borrowed">
                                        <h:outputText value="#{account.amountBorrowed}" />
                                    </p:column>
                                    <p:column headerText="Amount Repayed">
                                        <h:outputText value="#{account.amountRepayed}" />
                                    </p:column>
                                </p:dataTable>
                            </p:panel>
                        </h:form>
                    
                    </p:layoutUnit>
                </ui:define>
            </ui:decorate>
        
    </h:body>
</html>

SRC_Hubert/ACME_HomeLoanSystem/ACME_HomeLoanSystem-war/web/decor.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:fragment xmlns="http://www.w3.org/1999/xhtml"
             xmlns:ui="http://java.sun.com/jsf/facelets"
             xmlns:p="http://primefaces.org/ui">
    <p:layout>
        <ui:insert name="content">Content</ui:insert>
    </p:layout>
</ui:fragment>

SRC_Hubert/ACME_HomeLoanSystem/ACME_HomeLoanSystem-war/web/homeLoanWizard.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Create a Homeloan</title>
        <f:event type="preRenderView" listener="#{webLoginBean.isAuthenticated()}" />
        <f:event type="preRenderView" listener="#{webHomeLoanBean.requestForHLAccountCreation(webLoginBean.id)}" />
    </h:head>
    <h:body>
        
        <!-- Include the decoration container -->
            <ui:decorate template="decor.xhtml">
                <!-- A container for the content (content defined in decor.xhtml) -->
                <ui:define name="content">
                    <!-- include the menu -->
                    <ui:include src="menuBar.xhtml"/>
                    
                    <!-- Home page form -->
                    <p:layoutUnit position="center" resizable="false" style="min-height: 400px;max-height: available">
                        
                        <h:form>
                            <p:growl id="growl" sticky="true" showDetail="true"/>
                            
                            <p:wizard flowListener="#{webHomeLoanBean.onFlowProcess}">
                                <p:tab id="personal" title="Personal">
                                    <p:panel header="Personal Details">
                                        <h:messages errorClass="error"/>
                                        <h:panelGrid columns="2" columnClasses="label, value" styleClass="grid">
                                            
                                            <h:outputText value="Salutation: *" />
                                            <p:selectOneMenu value="#{webHomeLoanBean.user.salutation}" >
                                                <f:selectItem itemLabel="Select One" itemValue="" />
                                                <f:selectItems value="#{webHomeLoanBean.user.salutations}" />
                                            </p:selectOneMenu>
                                            
                                            <h:outputText value="Firstname: *" />
                                            <p:inputText required="true" label="Firstname"  
                                                    value="#{webHomeLoanBean.user.firstName}" />
                                            <h:outputText value="Middle Name: " />
                                            <p:inputText required="true" label="Firstname"  
                                                    value="#{webHomeLoanBean.user.middleName}" />
                                            <h:outputText value="Lastname: *" />
                                            <p:inputText required="true" label="Lastname"
                                                    value="#{webHomeLoanBean.user.lastName}" />
                                            <!-- we don't need age since we have DOB already
                                            <h:outputText value="Age: *" />
                                            <p:spinner id="age"
                                                 value="#{webHomeLoanBean.user.age}" min="18" max="108"/>  
                                            -->
                                            <h:outputText value="Date of birth: " />
                                            <p:calendar value="#{webHomeLoanBean.user.dob}" id="calDob" showOn="button" />
                                            
                                            <h:outputText value="Phone: " />
                                            <p:inputText required="true" label="Phone" value="#{webHomeLoanBean.user.phone}" id="phone" />
                                            
                                            <h:outputText value="E-mail: " />
                                            <p:inputText required="true" label="E-mail" value="#{webHomeLoanBean.user.email}" id="email" />
                                            
                                            <h:outputText value="Skip to last: " />
                                            <h:selectBooleanCheckbox value="#{webHomeLoanBean.skip}" />
                                        </h:panelGrid>
                                    </p:panel>
                                </p:tab>

                                <p:tab id="employment" title="employment">
                                    <p:panel header="Employment Details">
                                        <h:messages errorClass="error"/>
                                        
                                        <h:panelGrid columns="2" columnClasses="label, value">
                                            <h:outputText value="Company Name: " />
                                            <p:inputText value="#{webHomeLoanBean.user.companyName}" />
                                            
                                            <h:outputText value="Company Address: " />
                                            <p:inputText value="#{webHomeLoanBean.user.companyAddress}" />
                                            
                                            <!-- employment type Full-time/ part-time/ casual -->
                                            <h:outputText value="Employment Type: " />
                                            <p:selectOneMenu value="#{webHomeLoanBean.user.empType}" >
                                                <f:selectItem itemLabel="Select One" itemValue="" />
                                                <f:selectItems value="#{webHomeLoanBean.user.employmentTypes}"/>
                                            </p:selectOneMenu>
                                            
                                            <!-- Hours per week -->
                                            <h:outputText value="Hours per week: " />
                                            <p:spinner id="hours"
                                                 value="#{webHomeLoanBean.user.hoursPerWeek}" min="0" max="112"/>
                                            
                                            <h:outputText value="Job Title: " />
                                            <p:inputText value="#{webHomeLoanBean.user.jobTitle}" />

                                            <h:outputText value="Salary: " />
                                            <p:spinner id="salary"
                                                value="#{webHomeLoanBean.user.salary}" min="0"/>
                                            
                                            <h:outputText value="Employment Start Date: " />
                                            <p:calendar value="#{webHomeLoanBean.user.employmentStartDate}" id="calStartEmpDate" showOn="button" />
                                            
                                            <h:outputText value="Skip to last: " />  
                                            <h:selectBooleanCheckbox value="#{webHomeLoanBean.skip}" />  
                                        </h:panelGrid>  
                                    </p:panel>
                                </p:tab>  

                                <p:tab id="contact" title="Contact Method">  
                                    <p:panel header="Contact Method">
                                        
                                        <h:panelGrid columns="2"> 
                                            <h:outputText value="Preferred Contact Method:* " />
                                            <p:selectOneRadio id="customRadio" value="#{webHomeLoanBean.user.contactType}" layout="pageDirection">  
                                                <f:selectItems value="#{webHomeLoanBean.user.contactTypes}" />
                                            </p:selectOneRadio>
                                        </h:panelGrid>
                                        
                                        
                                    </p:panel>
                                </p:tab>
                                
                                <p:tab id="confirmation" title="Contact Method">  
                                    <p:panel header="Confirmation">
                                        
                                        <h:panelGrid columns="2">
                                            
                                            <h:outputText value="Loan Amount:  $" />
                                            <p:spinner id="loanamount"
                                                       min="0.0" required="true" requiredMessage="You must indicate a positive amount of money to borrow." value="#{webHomeLoanBean.user.loanAmount}" prefix="$" />
                                            
                                        </h:panelGrid>
                                        
                                        <p:scrollPanel style="background-color: #f2f4f9;width: available;height: 200px; border-style: solid; margin: 15px" >
                                            <h:outputText value="${webHomeLoanBean.user.termsMessage}" style="font-size: small; font-family: fantasy"/>
                                        </p:scrollPanel>
                                        
                                        <h:panelGrid columns="2">
                                            
                                            <h:outputText value="I hereby accept the terms and conditions above " />
                                            <p:selectBooleanCheckbox required="true" requiredMessage="You must agree to the terms to open a home loan." value="#{webHomeLoanBean.user.acceptedTerms}" />
                                        </h:panelGrid>
                                        
                                    </p:panel>
                                    
                                    <p:commandButton value="Submit" update="growl"
                                                    actionListener="#{webHomeLoanBean.submit(webLoginBean.id)}"/>
                                    
                                </p:tab>
                                
                            </p:wizard>
                        </h:form>
                    
                    </p:layoutUnit>
                </ui:define>
            </ui:decorate>
        
    </h:body>
</html>

SRC_Hubert/ACME_HomeLoanSystem/ACME_HomeLoanSystem-war/web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Login to ACME Banking System</title>
        <h:outputStylesheet library="css" name="styles.css" />
        <h:outputScript library="scripts" name="jscript.js" />
    </h:head>
    <h:body>
        <h3>Welcome to ACME Banking System</h3>
        <h:form id="f_login">
        <p:panel header="Login" toggleable="true" >
            <p:messages id="messages" autoUpdate="true" closable="true"/>
                <h:panelGrid columns="3" columnClasses="rightalign,leftalign,leftalign">
                    <h:outputLabel for="txtId" value="ID: "/>
                    <p:inputText id="txtId" label="ID" required="true" requiredMessage="Please Provide your User id, Eg; E01" value="#{webLoginBean.id}" >
                        <f:validateLength minimum="2" />
                    </p:inputText>
                    <p:message for="txtId" />
                    <h:outputLabel for="txtPassword" value="Password: "/>
                    <p:password id ="txtPassword" label="Password: " required="true" requiredMessage="Please enter your password" value="#{webLoginBean.password}" 
                                feedback="true" weakLabel="Your password is weak, you should consider changing it" goodLabel="Your password is good but it could be better" strongLabel="=D" inline="true"/>
                    <p:message for="txtPassword"  />
                    <p:commandButton id="login" value="Login"
                                     action="#{webLoginBean.initMe()}" icon="ui-icon-circle-check"/>
                </h:panelGrid>
        </p:panel>
        </h:form>
    </h:body>
</html>

SRC_Hubert/ACME_HomeLoanSystem/ACME_HomeLoanSystem-war/web/menuBar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!--<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> -->
<ui:fragment xmlns="http://www.w3.org/1999/xhtml"
             xmlns:p="http://primefaces.org/ui"
             xmlns:ui="http://java.sun.com/jsf/facelets"
             xmlns:h="http://java.sun.com/jsf/html"
             xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:form id="f_navbar">
        
        <p:layoutUnit position="north" resizable="false" style="height: auto">
            <p:menubar style="height: auto">
                 <p:menuitem value="Home" url="welcome.xhtml" style="margin-left:30px"/>
                 
                 <p:menuitem value="Create Home Loan" url="homeLoanWizard.xhtml" />

                 <p:menuitem value="Transactions" url="transactions.xhtml" />
                 
                 <p:menuitem value="About" url="about.xhtml"/>
                 
                 <!-- The logout option with search bar -->
                 <f:facet name="options">
                     <h:outputText value="#{webLoginBean.welcomeMessage}" style="margin-right:10px"/>
                     <p:button value="Logout" outcome="sessionTimeout" icon="ui-icon-extlink"/>
                 </f:facet>
            </p:menubar>
        </p:layoutUnit>
    </h:form>

</ui:fragment>

SRC_Hubert/ACME_HomeLoanSystem/ACME_HomeLoanSystem-war/web/newjsf.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
    </h:body>
</html>

SRC_Hubert/ACME_HomeLoanSystem/ACME_HomeLoanSystem-war/web/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Welcome to ACME banking!</title>
        <f:event type="preRenderView" listener="#{webLoginBean.isAuthenticated()}" />
    </h:head>
    <h:body>
        
        <!-- Include the decoration container -->
            <ui:decorate template="decor.xhtml">
                <!-- A container for the content (content defined in decor.xhtml) -->
                <ui:define name="content">
                    <!-- include the menu -->
                    <ui:include src="menuBar.xhtml"/>
                    
                    <!-- Home page form -->
                    <p:layoutUnit position="center" resizable="false" style="min-height: 400px;max-height: available">
                    <h:outputText value="#{webLoginBean.welcomeMessage}" />
                    
                        <h:form>
                            <h:panelGrid columns="3"
                                         columnClasses="rightalign,leftalign,leftalign">
                                <!--<h:commandButton id="refresh" value="Refresh"
                                                 action="welcome"/>-->
                                <h:commandButton id="logout" value="Logout"
                                                 action="#{webLoginBean.logout}"/>
                            </h:panelGrid>
                        </h:form>
                    
                    </p:layoutUnit>
                </ui:define>
            </ui:decorate>
        
    </h:body>
</html>