SRC_Hubert/ACME_HomeLoanSystem/ACME_HomeLoanSystem-war/src/java/jsf/HomeloanaccountsController.java
package jsf;

import jpa.Homeloanaccounts;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import beans.HomeloanaccountsFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("homeloanaccountsController")
@SessionScoped
public class HomeloanaccountsController implements Serializable {

    private Homeloanaccounts current;
    private DataModel items = null;
    @EJB
    private beans.HomeloanaccountsFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public HomeloanaccountsController() {
    }

    public Homeloanaccounts getSelected() {
        if (current == null) {
            current = new Homeloanaccounts();
            selectedItemIndex = -1;
        }
        return current;
    }

    private HomeloanaccountsFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Homeloanaccounts) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Homeloanaccounts();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("HomeloanaccountsCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Homeloanaccounts) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("HomeloanaccountsUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Homeloanaccounts) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("HomeloanaccountsDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Homeloanaccounts getHomeloanaccounts(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Homeloanaccounts.class)
    public static class HomeloanaccountsControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            HomeloanaccountsController controller = (HomeloanaccountsController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "homeloanaccountsController");
            return controller.getHomeloanaccounts(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Homeloanaccounts) {
                Homeloanaccounts o = (Homeloanaccounts) object;
                return getStringKey(o.getHlAcc());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Homeloanaccounts.class.getName());
            }
        }
    }
}

SRC_Hubert/ACME_HomeLoanSystem/ACME_HomeLoanSystem-war/web/homeloanaccounts/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateHomeloanaccountsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateHomeloanaccountsLabel_hlAcc}" for="hlAcc" />
                    <h:inputText id="hlAcc" value="#{homeloanaccountsController.selected.hlAcc}" title="#{bundle.CreateHomeloanaccountsTitle_hlAcc}" required="true" requiredMessage="#{bundle.CreateHomeloanaccountsRequiredMessage_hlAcc}"/>
                    <h:outputLabel value="#{bundle.CreateHomeloanaccountsLabel_amountborrowed}" for="amountborrowed" />
                    <h:inputText id="amountborrowed" value="#{homeloanaccountsController.selected.amountborrowed}" title="#{bundle.CreateHomeloanaccountsTitle_amountborrowed}" />
                    <h:outputLabel value="#{bundle.CreateHomeloanaccountsLabel_amountrepayed}" for="amountrepayed" />
                    <h:inputText id="amountrepayed" value="#{homeloanaccountsController.selected.amountrepayed}" title="#{bundle.CreateHomeloanaccountsTitle_amountrepayed}" />
                    <h:outputLabel value="#{bundle.CreateHomeloanaccountsLabel_CId}" for="CId" />
                    <h:selectOneMenu id="CId" value="#{homeloanaccountsController.selected.CId}" title="#{bundle.CreateHomeloanaccountsTitle_CId}" >
                        <f:selectItems value="#{customerinfoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{homeloanaccountsController.create}" value="#{bundle.CreateHomeloanaccountsSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{homeloanaccountsController.prepareList}" value="#{bundle.CreateHomeloanaccountsShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateHomeloanaccountsIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

SRC_Hubert/ACME_HomeLoanSystem/ACME_HomeLoanSystem-war/web/homeloanaccounts/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditHomeloanaccountsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditHomeloanaccountsLabel_hlAcc}" for="hlAcc" />
                    <h:inputText id="hlAcc" value="#{homeloanaccountsController.selected.hlAcc}" title="#{bundle.EditHomeloanaccountsTitle_hlAcc}" required="true" requiredMessage="#{bundle.EditHomeloanaccountsRequiredMessage_hlAcc}"/>
                    <h:outputLabel value="#{bundle.EditHomeloanaccountsLabel_amountborrowed}" for="amountborrowed" />
                    <h:inputText id="amountborrowed" value="#{homeloanaccountsController.selected.amountborrowed}" title="#{bundle.EditHomeloanaccountsTitle_amountborrowed}" />
                    <h:outputLabel value="#{bundle.EditHomeloanaccountsLabel_amountrepayed}" for="amountrepayed" />
                    <h:inputText id="amountrepayed" value="#{homeloanaccountsController.selected.amountrepayed}" title="#{bundle.EditHomeloanaccountsTitle_amountrepayed}" />
                    <h:outputLabel value="#{bundle.EditHomeloanaccountsLabel_CId}" for="CId" />
                    <h:selectOneMenu id="CId" value="#{homeloanaccountsController.selected.CId}" title="#{bundle.EditHomeloanaccountsTitle_CId}" >
                        <f:selectItems value="#{customerinfoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{homeloanaccountsController.update}" value="#{bundle.EditHomeloanaccountsSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditHomeloanaccountsViewLink}"/>
                <br />
                <h:commandLink action="#{homeloanaccountsController.prepareList}" value="#{bundle.EditHomeloanaccountsShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditHomeloanaccountsIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

SRC_Hubert/ACME_HomeLoanSystem/ACME_HomeLoanSystem-war/web/homeloanaccounts/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListHomeloanaccountsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListHomeloanaccountsEmpty}" rendered="#{homeloanaccountsController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{homeloanaccountsController.items.rowCount > 0}">
                    <h:outputText value="#{homeloanaccountsController.pagination.pageFirstItem + 1}..#{homeloanaccountsController.pagination.pageLastItem + 1}/#{homeloanaccountsController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{homeloanaccountsController.previous}" value="#{bundle.Previous} #{homeloanaccountsController.pagination.pageSize}" rendered="#{homeloanaccountsController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{homeloanaccountsController.next}" value="#{bundle.Next} #{homeloanaccountsController.pagination.pageSize}" rendered="#{homeloanaccountsController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{homeloanaccountsController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListHomeloanaccountsTitle_hlAcc}"/>
                            </f:facet>
                            <h:outputText value="#{item.hlAcc}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListHomeloanaccountsTitle_amountborrowed}"/>
                            </f:facet>
                            <h:outputText value="#{item.amountborrowed}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListHomeloanaccountsTitle_amountrepayed}"/>
                            </f:facet>
                            <h:outputText value="#{item.amountrepayed}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListHomeloanaccountsTitle_CId}"/>
                            </f:facet>
                            <h:outputText value="#{item.CId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{homeloanaccountsController.prepareView}" value="#{bundle.ListHomeloanaccountsViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{homeloanaccountsController.prepareEdit}" value="#{bundle.ListHomeloanaccountsEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{homeloanaccountsController.destroy}" value="#{bundle.ListHomeloanaccountsDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{homeloanaccountsController.prepareCreate}" value="#{bundle.ListHomeloanaccountsCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListHomeloanaccountsIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

SRC_Hubert/ACME_HomeLoanSystem/ACME_HomeLoanSystem-war/web/homeloanaccounts/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewHomeloanaccountsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewHomeloanaccountsLabel_hlAcc}"/>
                    <h:outputText value="#{homeloanaccountsController.selected.hlAcc}" title="#{bundle.ViewHomeloanaccountsTitle_hlAcc}"/>
                    <h:outputText value="#{bundle.ViewHomeloanaccountsLabel_amountborrowed}"/>
                    <h:outputText value="#{homeloanaccountsController.selected.amountborrowed}" title="#{bundle.ViewHomeloanaccountsTitle_amountborrowed}"/>
                    <h:outputText value="#{bundle.ViewHomeloanaccountsLabel_amountrepayed}"/>
                    <h:outputText value="#{homeloanaccountsController.selected.amountrepayed}" title="#{bundle.ViewHomeloanaccountsTitle_amountrepayed}"/>
                    <h:outputText value="#{bundle.ViewHomeloanaccountsLabel_CId}"/>
                    <h:outputText value="#{homeloanaccountsController.selected.CId}" title="#{bundle.ViewHomeloanaccountsTitle_CId}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{homeloanaccountsController.destroyAndView}" value="#{bundle.ViewHomeloanaccountsDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewHomeloanaccountsEditLink}"/>
                <br />
                <h:commandLink action="#{homeloanaccountsController.prepareCreate}" value="#{bundle.ViewHomeloanaccountsCreateLink}" />
                <br />
                <h:commandLink action="#{homeloanaccountsController.prepareList}" value="#{bundle.ViewHomeloanaccountsShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewHomeloanaccountsIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>